name: Array API Tests

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      pytest-extra-args:
        required: false
        type: string
      xfails-file:
        required: false
        type: string
        default: '${{ inputs.package-name }}-xfails.txt'
      skips-file:
        required: false
        type: string
        default: '${{ inputs.package-name }}-skips.txt'

env:
  PYTEST_ARGS: "--max-examples 200 -v -rxXfE --ci ${{ inputs.pytest-extra-args }}"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout array-api-compat
      uses: actions/checkout@v3
      with:
        path: array-api-compat
    - name: Checkout array-api-tests
      uses: actions/checkout@v3
      with:
        # repository: data-apis/array-api-tests
        submodules: 'true'
        path: array-api-tests

        # Temporarily use https://github.com/data-apis/array-api-tests/pull/157
        repository: asmeurer/array-api-tests
        ref: xfails-file
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ${{ inputs.package-name }}
        python -m pip install -r ${GITHUB_WORKSPACE}/array-api-tests/requirements.txt
    - name: Run the array API testsuite (${{ inputs.package-name }})
      env:
        ARRAY_API_TESTS_MODULE: array_api_compat.${{ inputs.package-name }}
        # This enables the NEP 50 type promotion behavior (without it a lot of
        # tests fail on bad scalar type promotion behavior)
        NPY_PROMOTION_STATE: weak
      run: |
        export PYTHONPATH="${GITHUB_WORKSPACE}/array-api-compat"
        cd ${GITHUB_WORKSPACE}/array-api-tests
        pytest ${PYTEST_ARGS} --xfails-file ${GITHUB_WORKSPACE}/array-api-compat/${{ inputs.xfails-file }} --skips-file ${GITHUB_WORKSPACE}/array-api-compat/${{ inputs.skips-file }} array_api_tests/
